aded forgot password endpoints
learnhubmkd/api pull request #134
Opened 2024-07-30 21:48 UTC by calexandar

#49 
#109

2024-07-30 21:59 UTC, davorminchorov requested changes

2024-07-30 21:59 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +                ])->setRememberToken(Str::random(60));
I don't think we need the remember password part since it's an API endpoint.

2024-07-30 21:59 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/PasswordResetLinkController.php
> +        $request->validated();
You are not using the result of the request data so this line can be deleted.

2024-07-30 21:59 UTC, davorminchorov commented on app/Authentication/src/Http/Responses/FailedPasswordResetResponse.php
> +                    : redirect()->route('login')->with('status', trans($this->status));
This is not needed since it's an API only project. The line above can be the returned result.

2024-07-30 21:59 UTC, davorminchorov commented on app/Authentication/src/Http/Responses/FailedPasswordResetLinkRequestResponse.php
> +        return back()
This is not needed since it's an API only project. The line above can be the returned result.

2024-07-30 21:59 UTC, davorminchorov commented on app/Authentication/src/Http/Responses/PasswordResetResponse.php
> +        return back()
This is not needed since it's an API only project. The line above can be the returned result.

2024-07-30 21:59 UTC, davorminchorov commented on app/Authentication/src/Http/Responses/SuccessfulPasswordResetLinkRequestResponse.php
> +                    : back()->with('status', trans($this->status));
This is not needed since it's an API only project. The line above can be the returned result.

2024-08-02 10:58 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +    #[BodyParam('email', 'password', 'token',  required: true)]
Does this work or should there be 3 body param attributes separately?

2024-08-02 10:58 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +        $request->validated();
You don't need this line. It returns an array of validated values which you are not using them.

2024-08-02 10:58 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +                $user->fill([
You can use `update()` directly

2024-08-02 10:58 UTC, davorminchorov commented
Don't forget to fix the styles with Laravel Pint.

2024-08-05 15:20 UTC, calexandar commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +    #[BodyParam('email', 'password', 'token',  required: true)]
Yes it works with 3 params plus password_confirmation. But I wasn't able to add here scribe doesn't like the word password two times. I need to figure out how to buypass this issue.

2024-08-05 15:23 UTC, davorminchorov commented on app/Authentication/routes/authentication-routes.php
> +    Route::post('/reset-password', NewPasswordController::class)->withoutMiddleware(['auth:api']);
I think the names of the URLs can be better:
1. `/passwords/request-new`
2. `/passwords/reset`

What do you think?

2024-08-05 15:24 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +                $user->save();
You don't need the save anymore, you are already doing the update above.

2024-08-05 15:41 UTC, davorminchorov commented on app/Authentication/src/Http/Controllers/NewPasswordController.php
> +    #[BodyParam('email', 'password', 'token',  required: true)]
You would have to add the two separate fields (password and password_confirmation) in that case. If it works with all 3 values like that then it's ok, no need to split them.

2024-08-05 15:46 UTC, calexandar commented on app/Authentication/routes/authentication-routes.php
> +    Route::post('/reset-password', NewPasswordController::class)->withoutMiddleware(['auth:api']);
Yes we can change this I didn't like it either. I just copied from the docs.

2024-08-05 15:54 UTC, davorminchorov approved these changes

2024-08-05 15:54 UTC, merged